// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/agentmesh/v1/control_plane.proto

package agentmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthState describes an agent's runtime health.
type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_HEALTHY     HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2
	HealthState_HEALTH_STATE_UNHEALTHY   HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_HEALTHY",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_UNHEALTHY",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_HEALTHY":     1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_UNHEALTHY":   3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agentmesh_v1_control_plane_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_proto_agentmesh_v1_control_plane_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest is sent by a sidecar when its local agent starts up.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this agent instance.
	// Convention: <agent-name>-<pod-uid>.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Capabilities advertised by this agent (e.g., "search", "summarize").
	Capabilities []string `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Network endpoint where this agent (via its sidecar) receives A2A traffic.
	// Typically a Kubernetes Service or Pod IP plus port.
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Free-form metadata describing the agent (framework, version, etc.).
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RegisterResponse is returned to the sidecar after a successful registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque lease handle. Must be supplied on subsequent Heartbeat calls.
	LeaseId string `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Lease time-to-live in seconds. The sidecar should send Heartbeats more
	// frequently than this value (typical: at 1/3 of TTL).
	LeaseTtlSeconds int32 `protobuf:"varint,2,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *RegisterResponse) GetLeaseTtlSeconds() int32 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

// HeartbeatRequest is sent by a sidecar at a regular interval to refresh
// its agent's registration.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent that is heartbeating; must match a prior Register call.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// The lease handle returned by Register.
	LeaseId string `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	// Current health state of the agent.
	Health HealthState `protobuf:"varint,3,opt,name=health,proto3,enum=agentmesh.v1.HealthState" json:"health,omitempty"`
	// Normalized load metric in [0.0, 1.0]. Used by the routing engine
	// for least-loaded selection in later milestones.
	Load          float64 `protobuf:"fixed64,4,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *HeartbeatRequest) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *HeartbeatRequest) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

// HeartbeatResponse acknowledges a heartbeat and returns the refreshed TTL.
type HeartbeatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeaseTtlSeconds int32                  `protobuf:"varint,1,opt,name=lease_ttl_seconds,json=leaseTtlSeconds,proto3" json:"lease_ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_control_plane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetLeaseTtlSeconds() int32 {
	if x != nil {
		return x.LeaseTtlSeconds
	}
	return 0
}

var File_proto_agentmesh_v1_control_plane_proto protoreflect.FileDescriptor

const file_proto_agentmesh_v1_control_plane_proto_rawDesc = "" +
	"\n" +
	"&proto/agentmesh/v1/control_plane.proto\x12\fagentmesh.v1\"\xf2\x01\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12G\n" +
	"\bmetadata\x18\x04 \x03(\v2+.agentmesh.v1.RegisterRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12*\n" +
	"\x11lease_ttl_seconds\x18\x02 \x01(\x05R\x0fleaseTtlSeconds\"\x8f\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x121\n" +
	"\x06health\x18\x03 \x01(\x0e2\x19.agentmesh.v1.HealthStateR\x06health\x12\x12\n" +
	"\x04load\x18\x04 \x01(\x01R\x04load\"?\n" +
	"\x11HeartbeatResponse\x12*\n" +
	"\x11lease_ttl_seconds\x18\x01 \x01(\x05R\x0fleaseTtlSeconds*|\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x032\xa7\x01\n" +
	"\fControlPlane\x12I\n" +
	"\bRegister\x12\x1d.agentmesh.v1.RegisterRequest\x1a\x1e.agentmesh.v1.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.agentmesh.v1.HeartbeatRequest\x1a\x1f.agentmesh.v1.HeartbeatResponseB>Z<github.com/neontvn/agent-mesh/proto/agentmesh/v1;agentmeshv1b\x06proto3"

var (
	file_proto_agentmesh_v1_control_plane_proto_rawDescOnce sync.Once
	file_proto_agentmesh_v1_control_plane_proto_rawDescData []byte
)

func file_proto_agentmesh_v1_control_plane_proto_rawDescGZIP() []byte {
	file_proto_agentmesh_v1_control_plane_proto_rawDescOnce.Do(func() {
		file_proto_agentmesh_v1_control_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentmesh_v1_control_plane_proto_rawDesc), len(file_proto_agentmesh_v1_control_plane_proto_rawDesc)))
	})
	return file_proto_agentmesh_v1_control_plane_proto_rawDescData
}

var file_proto_agentmesh_v1_control_plane_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_agentmesh_v1_control_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_agentmesh_v1_control_plane_proto_goTypes = []any{
	(HealthState)(0),          // 0: agentmesh.v1.HealthState
	(*RegisterRequest)(nil),   // 1: agentmesh.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: agentmesh.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: agentmesh.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: agentmesh.v1.HeartbeatResponse
	nil,                       // 5: agentmesh.v1.RegisterRequest.MetadataEntry
}
var file_proto_agentmesh_v1_control_plane_proto_depIdxs = []int32{
	5, // 0: agentmesh.v1.RegisterRequest.metadata:type_name -> agentmesh.v1.RegisterRequest.MetadataEntry
	0, // 1: agentmesh.v1.HeartbeatRequest.health:type_name -> agentmesh.v1.HealthState
	1, // 2: agentmesh.v1.ControlPlane.Register:input_type -> agentmesh.v1.RegisterRequest
	3, // 3: agentmesh.v1.ControlPlane.Heartbeat:input_type -> agentmesh.v1.HeartbeatRequest
	2, // 4: agentmesh.v1.ControlPlane.Register:output_type -> agentmesh.v1.RegisterResponse
	4, // 5: agentmesh.v1.ControlPlane.Heartbeat:output_type -> agentmesh.v1.HeartbeatResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agentmesh_v1_control_plane_proto_init() }
func file_proto_agentmesh_v1_control_plane_proto_init() {
	if File_proto_agentmesh_v1_control_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentmesh_v1_control_plane_proto_rawDesc), len(file_proto_agentmesh_v1_control_plane_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentmesh_v1_control_plane_proto_goTypes,
		DependencyIndexes: file_proto_agentmesh_v1_control_plane_proto_depIdxs,
		EnumInfos:         file_proto_agentmesh_v1_control_plane_proto_enumTypes,
		MessageInfos:      file_proto_agentmesh_v1_control_plane_proto_msgTypes,
	}.Build()
	File_proto_agentmesh_v1_control_plane_proto = out.File
	file_proto_agentmesh_v1_control_plane_proto_goTypes = nil
	file_proto_agentmesh_v1_control_plane_proto_depIdxs = nil
}
