// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/agentmesh/v1/control_plane.proto

package agentmeshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlane_Register_FullMethodName     = "/agentmesh.v1.ControlPlane/Register"
	ControlPlane_Heartbeat_FullMethodName    = "/agentmesh.v1.ControlPlane/Heartbeat"
	ControlPlane_Discover_FullMethodName     = "/agentmesh.v1.ControlPlane/Discover"
	ControlPlane_SelectTarget_FullMethodName = "/agentmesh.v1.ControlPlane/SelectTarget"
	ControlPlane_ReportInvoke_FullMethodName = "/agentmesh.v1.ControlPlane/ReportInvoke"
)

// ControlPlaneClient is the client API for ControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlane is the gRPC service exposed by the AgentMesh control plane
// to sidecar data planes running alongside each agent.
type ControlPlaneClient interface {
	// Register registers an agent with the control plane. The control plane
	// materializes the registration as an Agent CRD in the Kubernetes cluster
	// and returns a lease handle that the sidecar must refresh via Heartbeat.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat refreshes the lease of a previously-registered agent. If a
	// heartbeat is not received within the lease TTL, the control plane marks
	// the agent unhealthy and removes it from the active pool.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Discover returns all healthy agents advertising the requested
	// capability. Used by sidecars that maintain a local routing cache.
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// SelectTarget returns a single agent chosen by the control plane's
	// routing policy (round-robin in v0) from the healthy agents advertising
	// the requested capability. Used by sidecars that defer routing to the
	// control plane.
	SelectTarget(ctx context.Context, in *SelectTargetRequest, opts ...grpc.CallOption) (*SelectTargetResponse, error)
	// ReportInvoke is called by a sidecar after each A2A Invoke completes
	// so the control plane can broadcast routing events to observability
	// subscribers (the live UI, metrics, traces).
	ReportInvoke(ctx context.Context, in *ReportInvokeRequest, opts ...grpc.CallOption) (*ReportInvokeResponse, error)
}

type controlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneClient(cc grpc.ClientConnInterface) ControlPlaneClient {
	return &controlPlaneClient{cc}
}

func (c *controlPlaneClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, ControlPlane_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) SelectTarget(ctx context.Context, in *SelectTargetRequest, opts ...grpc.CallOption) (*SelectTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectTargetResponse)
	err := c.cc.Invoke(ctx, ControlPlane_SelectTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneClient) ReportInvoke(ctx context.Context, in *ReportInvokeRequest, opts ...grpc.CallOption) (*ReportInvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInvokeResponse)
	err := c.cc.Invoke(ctx, ControlPlane_ReportInvoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServer is the server API for ControlPlane service.
// All implementations must embed UnimplementedControlPlaneServer
// for forward compatibility.
//
// ControlPlane is the gRPC service exposed by the AgentMesh control plane
// to sidecar data planes running alongside each agent.
type ControlPlaneServer interface {
	// Register registers an agent with the control plane. The control plane
	// materializes the registration as an Agent CRD in the Kubernetes cluster
	// and returns a lease handle that the sidecar must refresh via Heartbeat.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat refreshes the lease of a previously-registered agent. If a
	// heartbeat is not received within the lease TTL, the control plane marks
	// the agent unhealthy and removes it from the active pool.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Discover returns all healthy agents advertising the requested
	// capability. Used by sidecars that maintain a local routing cache.
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	// SelectTarget returns a single agent chosen by the control plane's
	// routing policy (round-robin in v0) from the healthy agents advertising
	// the requested capability. Used by sidecars that defer routing to the
	// control plane.
	SelectTarget(context.Context, *SelectTargetRequest) (*SelectTargetResponse, error)
	// ReportInvoke is called by a sidecar after each A2A Invoke completes
	// so the control plane can broadcast routing events to observability
	// subscribers (the live UI, metrics, traces).
	ReportInvoke(context.Context, *ReportInvokeRequest) (*ReportInvokeResponse, error)
	mustEmbedUnimplementedControlPlaneServer()
}

// UnimplementedControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServer struct{}

func (UnimplementedControlPlaneServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedControlPlaneServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedControlPlaneServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedControlPlaneServer) SelectTarget(context.Context, *SelectTargetRequest) (*SelectTargetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectTarget not implemented")
}
func (UnimplementedControlPlaneServer) ReportInvoke(context.Context, *ReportInvokeRequest) (*ReportInvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInvoke not implemented")
}
func (UnimplementedControlPlaneServer) mustEmbedUnimplementedControlPlaneServer() {}
func (UnimplementedControlPlaneServer) testEmbeddedByValue()                      {}

// UnsafeControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServer will
// result in compilation errors.
type UnsafeControlPlaneServer interface {
	mustEmbedUnimplementedControlPlaneServer()
}

func RegisterControlPlaneServer(s grpc.ServiceRegistrar, srv ControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlane_ServiceDesc, srv)
}

func _ControlPlane_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_SelectTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).SelectTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_SelectTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).SelectTarget(ctx, req.(*SelectTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlane_ReportInvoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServer).ReportInvoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlane_ReportInvoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServer).ReportInvoke(ctx, req.(*ReportInvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlane_ServiceDesc is the grpc.ServiceDesc for ControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentmesh.v1.ControlPlane",
	HandlerType: (*ControlPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _ControlPlane_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ControlPlane_Heartbeat_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _ControlPlane_Discover_Handler,
		},
		{
			MethodName: "SelectTarget",
			Handler:    _ControlPlane_SelectTarget_Handler,
		},
		{
			MethodName: "ReportInvoke",
			Handler:    _ControlPlane_ReportInvoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agentmesh/v1/control_plane.proto",
}
