// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/agentmesh/v1/data_plane.proto

package agentmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvokeRequest carries a capability invocation from one agent to another.
type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The capability being invoked (e.g., "search").
	Capability string `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	// Opaque payload — the inputs to the capability. The local agent
	// application determines the format.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Per-request metadata (correlation ID, session ID, etc.).
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_agentmesh_v1_data_plane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_data_plane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_data_plane_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InvokeResponse carries the result of a capability invocation back to the
// caller's sidecar.
type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque result payload. The caller agent application interprets it.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// Per-response metadata.
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_agentmesh_v1_data_plane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentmesh_v1_data_plane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentmesh_v1_data_plane_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_agentmesh_v1_data_plane_proto protoreflect.FileDescriptor

const file_proto_agentmesh_v1_data_plane_proto_rawDesc = "" +
	"\n" +
	"#proto/agentmesh/v1/data_plane.proto\x12\fagentmesh.v1\"\xcd\x01\n" +
	"\rInvokeRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).agentmesh.v1.InvokeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x0eInvokeResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12F\n" +
	"\bmetadata\x18\x02 \x03(\v2*.agentmesh.v1.InvokeResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012U\n" +
	"\x0eAgentDataPlane\x12C\n" +
	"\x06Invoke\x12\x1b.agentmesh.v1.InvokeRequest\x1a\x1c.agentmesh.v1.InvokeResponseB>Z<github.com/neontvn/agent-mesh/proto/agentmesh/v1;agentmeshv1b\x06proto3"

var (
	file_proto_agentmesh_v1_data_plane_proto_rawDescOnce sync.Once
	file_proto_agentmesh_v1_data_plane_proto_rawDescData []byte
)

func file_proto_agentmesh_v1_data_plane_proto_rawDescGZIP() []byte {
	file_proto_agentmesh_v1_data_plane_proto_rawDescOnce.Do(func() {
		file_proto_agentmesh_v1_data_plane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentmesh_v1_data_plane_proto_rawDesc), len(file_proto_agentmesh_v1_data_plane_proto_rawDesc)))
	})
	return file_proto_agentmesh_v1_data_plane_proto_rawDescData
}

var file_proto_agentmesh_v1_data_plane_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_agentmesh_v1_data_plane_proto_goTypes = []any{
	(*InvokeRequest)(nil),  // 0: agentmesh.v1.InvokeRequest
	(*InvokeResponse)(nil), // 1: agentmesh.v1.InvokeResponse
	nil,                    // 2: agentmesh.v1.InvokeRequest.MetadataEntry
	nil,                    // 3: agentmesh.v1.InvokeResponse.MetadataEntry
}
var file_proto_agentmesh_v1_data_plane_proto_depIdxs = []int32{
	2, // 0: agentmesh.v1.InvokeRequest.metadata:type_name -> agentmesh.v1.InvokeRequest.MetadataEntry
	3, // 1: agentmesh.v1.InvokeResponse.metadata:type_name -> agentmesh.v1.InvokeResponse.MetadataEntry
	0, // 2: agentmesh.v1.AgentDataPlane.Invoke:input_type -> agentmesh.v1.InvokeRequest
	1, // 3: agentmesh.v1.AgentDataPlane.Invoke:output_type -> agentmesh.v1.InvokeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agentmesh_v1_data_plane_proto_init() }
func file_proto_agentmesh_v1_data_plane_proto_init() {
	if File_proto_agentmesh_v1_data_plane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentmesh_v1_data_plane_proto_rawDesc), len(file_proto_agentmesh_v1_data_plane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentmesh_v1_data_plane_proto_goTypes,
		DependencyIndexes: file_proto_agentmesh_v1_data_plane_proto_depIdxs,
		MessageInfos:      file_proto_agentmesh_v1_data_plane_proto_msgTypes,
	}.Build()
	File_proto_agentmesh_v1_data_plane_proto = out.File
	file_proto_agentmesh_v1_data_plane_proto_goTypes = nil
	file_proto_agentmesh_v1_data_plane_proto_depIdxs = nil
}
