// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/agentmesh/v1/data_plane.proto

package agentmeshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentDataPlane_Invoke_FullMethodName = "/agentmesh.v1.AgentDataPlane/Invoke"
)

// AgentDataPlaneClient is the client API for AgentDataPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentDataPlane is the gRPC service exposed by each agent's sidecar to
// receive inbound agent-to-agent (A2A) calls from peer sidecars. The
// sidecar handles transport; the local agent application handles semantics.
type AgentDataPlaneClient interface {
	// Invoke dispatches a capability call to the local agent and returns
	// the result.
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
}

type agentDataPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentDataPlaneClient(cc grpc.ClientConnInterface) AgentDataPlaneClient {
	return &agentDataPlaneClient{cc}
}

func (c *agentDataPlaneClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, AgentDataPlane_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentDataPlaneServer is the server API for AgentDataPlane service.
// All implementations must embed UnimplementedAgentDataPlaneServer
// for forward compatibility.
//
// AgentDataPlane is the gRPC service exposed by each agent's sidecar to
// receive inbound agent-to-agent (A2A) calls from peer sidecars. The
// sidecar handles transport; the local agent application handles semantics.
type AgentDataPlaneServer interface {
	// Invoke dispatches a capability call to the local agent and returns
	// the result.
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	mustEmbedUnimplementedAgentDataPlaneServer()
}

// UnimplementedAgentDataPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentDataPlaneServer struct{}

func (UnimplementedAgentDataPlaneServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedAgentDataPlaneServer) mustEmbedUnimplementedAgentDataPlaneServer() {}
func (UnimplementedAgentDataPlaneServer) testEmbeddedByValue()                        {}

// UnsafeAgentDataPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentDataPlaneServer will
// result in compilation errors.
type UnsafeAgentDataPlaneServer interface {
	mustEmbedUnimplementedAgentDataPlaneServer()
}

func RegisterAgentDataPlaneServer(s grpc.ServiceRegistrar, srv AgentDataPlaneServer) {
	// If the following call panics, it indicates UnimplementedAgentDataPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentDataPlane_ServiceDesc, srv)
}

func _AgentDataPlane_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentDataPlaneServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentDataPlane_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentDataPlaneServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentDataPlane_ServiceDesc is the grpc.ServiceDesc for AgentDataPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentDataPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentmesh.v1.AgentDataPlane",
	HandlerType: (*AgentDataPlaneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _AgentDataPlane_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/agentmesh/v1/data_plane.proto",
}
