# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agentmesh.v1 import control_plane_pb2 as agentmesh_dot_v1_dot_control__plane__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentmesh/v1/control_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneStub:
    """ControlPlane is the gRPC service exposed by the AgentMesh control plane
    to sidecar data planes running alongside each agent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/agentmesh.v1.ControlPlane/Register',
                request_serializer=agentmesh_dot_v1_dot_control__plane__pb2.RegisterRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/agentmesh.v1.ControlPlane/Heartbeat',
                request_serializer=agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Discover = channel.unary_unary(
                '/agentmesh.v1.ControlPlane/Discover',
                request_serializer=agentmesh_dot_v1_dot_control__plane__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.DiscoverResponse.FromString,
                _registered_method=True)
        self.SelectTarget = channel.unary_unary(
                '/agentmesh.v1.ControlPlane/SelectTarget',
                request_serializer=agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetResponse.FromString,
                _registered_method=True)
        self.ReportInvoke = channel.unary_unary(
                '/agentmesh.v1.ControlPlane/ReportInvoke',
                request_serializer=agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeResponse.FromString,
                _registered_method=True)


class ControlPlaneServicer:
    """ControlPlane is the gRPC service exposed by the AgentMesh control plane
    to sidecar data planes running alongside each agent.
    """

    def Register(self, request, context):
        """Register registers an agent with the control plane. The control plane
        materializes the registration as an Agent CRD in the Kubernetes cluster
        and returns a lease handle that the sidecar must refresh via Heartbeat.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Heartbeat refreshes the lease of a previously-registered agent. If a
        heartbeat is not received within the lease TTL, the control plane marks
        the agent unhealthy and removes it from the active pool.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Discover(self, request, context):
        """Discover returns all healthy agents advertising the requested
        capability. Used by sidecars that maintain a local routing cache.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectTarget(self, request, context):
        """SelectTarget returns a single agent chosen by the control plane's
        routing policy (round-robin in v0) from the healthy agents advertising
        the requested capability. Used by sidecars that defer routing to the
        control plane.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportInvoke(self, request, context):
        """ReportInvoke is called by a sidecar after each A2A Invoke completes
        so the control plane can broadcast routing events to observability
        subscribers (the live UI, metrics, traces).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.RegisterRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_control__plane__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.DiscoverRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_control__plane__pb2.DiscoverResponse.SerializeToString,
            ),
            'SelectTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectTarget,
                    request_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetResponse.SerializeToString,
            ),
            'ReportInvoke': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportInvoke,
                    request_deserializer=agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmesh.v1.ControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmesh.v1.ControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlane:
    """ControlPlane is the gRPC service exposed by the AgentMesh control plane
    to sidecar data planes running alongside each agent.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.ControlPlane/Register',
            agentmesh_dot_v1_dot_control__plane__pb2.RegisterRequest.SerializeToString,
            agentmesh_dot_v1_dot_control__plane__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.ControlPlane/Heartbeat',
            agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatRequest.SerializeToString,
            agentmesh_dot_v1_dot_control__plane__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.ControlPlane/Discover',
            agentmesh_dot_v1_dot_control__plane__pb2.DiscoverRequest.SerializeToString,
            agentmesh_dot_v1_dot_control__plane__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.ControlPlane/SelectTarget',
            agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetRequest.SerializeToString,
            agentmesh_dot_v1_dot_control__plane__pb2.SelectTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportInvoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.ControlPlane/ReportInvoke',
            agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeRequest.SerializeToString,
            agentmesh_dot_v1_dot_control__plane__pb2.ReportInvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
