# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agentmesh/v1/data_plane.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'agentmesh/v1/data_plane.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x61gentmesh/v1/data_plane.proto\x12\x0c\x61gentmesh.v1\"\xa2\x01\n\rInvokeRequest\x12\x12\n\ncapability\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12;\n\x08metadata\x18\x03 \x03(\x0b\x32).agentmesh.v1.InvokeRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x90\x01\n\x0eInvokeResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12<\n\x08metadata\x18\x02 \x03(\x0b\x32*.agentmesh.v1.InvokeResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32U\n\x0e\x41gentDataPlane\x12\x43\n\x06Invoke\x12\x1b.agentmesh.v1.InvokeRequest\x1a\x1c.agentmesh.v1.InvokeResponseB>Z<github.com/neontvn/agent-mesh/proto/agentmesh/v1;agentmeshv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agentmesh.v1.data_plane_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/neontvn/agent-mesh/proto/agentmesh/v1;agentmeshv1'
  _globals['_INVOKEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INVOKERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_INVOKERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_INVOKEREQUEST']._serialized_start=48
  _globals['_INVOKEREQUEST']._serialized_end=210
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_start=163
  _globals['_INVOKEREQUEST_METADATAENTRY']._serialized_end=210
  _globals['_INVOKERESPONSE']._serialized_start=213
  _globals['_INVOKERESPONSE']._serialized_end=357
  _globals['_INVOKERESPONSE_METADATAENTRY']._serialized_start=163
  _globals['_INVOKERESPONSE_METADATAENTRY']._serialized_end=210
  _globals['_AGENTDATAPLANE']._serialized_start=359
  _globals['_AGENTDATAPLANE']._serialized_end=444
# @@protoc_insertion_point(module_scope)
