# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agentmesh.v1 import data_plane_pb2 as agentmesh_dot_v1_dot_data__plane__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agentmesh/v1/data_plane_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentDataPlaneStub:
    """AgentDataPlane is the gRPC service exposed by each agent's sidecar to
    receive inbound agent-to-agent (A2A) calls from peer sidecars. The
    sidecar handles transport; the local agent application handles semantics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Invoke = channel.unary_unary(
                '/agentmesh.v1.AgentDataPlane/Invoke',
                request_serializer=agentmesh_dot_v1_dot_data__plane__pb2.InvokeRequest.SerializeToString,
                response_deserializer=agentmesh_dot_v1_dot_data__plane__pb2.InvokeResponse.FromString,
                _registered_method=True)


class AgentDataPlaneServicer:
    """AgentDataPlane is the gRPC service exposed by each agent's sidecar to
    receive inbound agent-to-agent (A2A) calls from peer sidecars. The
    sidecar handles transport; the local agent application handles semantics.
    """

    def Invoke(self, request, context):
        """Invoke dispatches a capability call to the local agent and returns
        the result.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentDataPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Invoke': grpc.unary_unary_rpc_method_handler(
                    servicer.Invoke,
                    request_deserializer=agentmesh_dot_v1_dot_data__plane__pb2.InvokeRequest.FromString,
                    response_serializer=agentmesh_dot_v1_dot_data__plane__pb2.InvokeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentmesh.v1.AgentDataPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentmesh.v1.AgentDataPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentDataPlane:
    """AgentDataPlane is the gRPC service exposed by each agent's sidecar to
    receive inbound agent-to-agent (A2A) calls from peer sidecars. The
    sidecar handles transport; the local agent application handles semantics.
    """

    @staticmethod
    def Invoke(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentmesh.v1.AgentDataPlane/Invoke',
            agentmesh_dot_v1_dot_data__plane__pb2.InvokeRequest.SerializeToString,
            agentmesh_dot_v1_dot_data__plane__pb2.InvokeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
